import os
import glob
import pandas as pd
import numpy as np

# Import from your backend engine
from backend_ai_bot import (
    MasterConfig,
    DarwinEngine,
    QuantMath,
    SniperEngine,
    MonteCarloEngine,
    Backtester
)

def load_and_prep_csv(csv_path: str) -> pd.DataFrame:
    """Parses individual stock CSVs and standardizes columns for QuantMath."""
    df = pd.read_csv(csv_path)
    
    # Map lowercase headers to engine expectations
    rename_map = {
        'datetime': 'Date',
        'open': 'Open',
        'high': 'High',
        'low': 'Low',
        'close': 'Close',
        'volume': 'Volume'
    }
    df = df.rename(columns=rename_map)
    
    if 'Date' in df.columns:
        df['Date'] = pd.to_datetime(df['Date'])
        df = df.sort_values('Date').reset_index(drop=True)
        
    cols_to_keep = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']
    df = df[[c for c in cols_to_keep if c in df.columns]]
    
    for col in ['Open', 'High', 'Low', 'Close', 'Volume']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
            
    return df.dropna()

def train_on_historical_universe(data_dir: str, generations: int = 30, batch_size: int = 5):
    # Search for all CSV files (including in subdirectories)
    search_pattern = os.path.join(data_dir, "**", "*.csv")
    csv_files = glob.glob(search_pattern, recursive=True)
    
    # Exclude log CSVs generated by the trading engine
    csv_files = [f for f in csv_files if not os.path.basename(f).startswith("202") and "logs" not in f]

    print(f"📁 Found {len(csv_files)} valid stock files for training.")
    
    if len(csv_files) == 0:
        print(f"\n❌ Error: No CSV files found in '{os.path.abspath(data_dir)}'.")
        print("👉 Please check where your stock CSVs are located and update 'data_dir'.")
        return None

    cfg = MasterConfig()
    darwin = DarwinEngine()
    quant = QuantMath()
    sniper = SniperEngine()
    mc = MonteCarloEngine(simulations=300)  # Optimized simulation count for speed
    
    best_fitness = -float("inf")
    best_dna = dict(darwin.dna)
    
    print("\n" + "═"*60)
    print("  🧬 STARTING MULTI-SYMBOL DARWIN EVOLUTION")
    print("═"*60)
    
    for gen in range(1, generations + 1):
        gen_pnl = 0.0
        gen_trades = 0
        gen_wins = 0
        
        # Sample a random mini-batch of stocks to prevent single-stock overfitting
        current_batch_size = min(batch_size, len(csv_files))
        batch_files = np.random.choice(csv_files, size=current_batch_size, replace=False)
        
        for file in batch_files:
            try:
                df = load_and_prep_csv(file)
                if len(df) < 300:
                    continue
                    
                # In-sample historical slice (80% training)
                split_idx = int(len(df) * 0.80)
                train_df = df.iloc[:split_idx].reset_index(drop=True)
                
                bt = Backtester(cfg, darwin, quant, sniper, mc)
                res = bt.run(train_df, label=f"GEN_{gen} | {os.path.basename(file)}")
                
                gen_pnl += res["total_pnl"]
                gen_trades += res["trades"]
                gen_wins += int(res["trades"] * res["win_rate"])
            except Exception as e:
                continue
            
        if gen_trades == 0:
            continue

        overall_wr = gen_wins / gen_trades
        # Multi-objective fitness function (PnL weighted by Win Rate)
        fitness = gen_pnl * (overall_wr ** 1.5)
        
        if fitness > best_fitness:
            best_fitness = fitness
            best_dna = dict(darwin.dna)
            print(f"⭐ New Best DNA (Gen {gen}) | Fitness: {fitness:,.2f} | WR: {overall_wr:.1%} | PnL: ₹{gen_pnl:,.2f}")
        else:
            darwin.mutate(fitness)

    print("\n" + "═"*60)
    print("✅ FINAL OPTIMAL DNA PARAMETERS:")
    print("═"*60)
    print(best_dna)
    return best_dna

if __name__ == "__main__":
    # Specify the exact path to your CSV dataset folder here:
    # e.g., "./data", "/Users/yourname/Downloads/stock_csvs", or "."
    DATASET_PATH = "./" 
    
    train_on_historical_universe(data_dir=DATASET_PATH, generations=30, batch_size=5)